name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
    - name: Lint Action
      run: echo test
     
